### PR TITLE
New slot SlotMFlat2

### PR DESCRIPTION
**Pull request by mxgnsr**
Flat bottomed SlotMag with adjustable slot opening (for spoke type IPMSM) #158

### CODE REVIEW

**Comment by mxgnsr** [comment]
Sorry for disregarding the commit message conventions... I didn't plan to release it by then... I will do better next time!

**Comment by SebGue** [comment]
Hello Max,

it seems you haven't run black. Could you do that and commit these 'changes' as well?

BR Sebastian

**Comment by BonneelP** [comment]
Hello Max, 

Thank you for your contribution :) No problem for the commit message convention, at the end it doesn't affect the code ;)

I have only one remark to improve your PR:
- Tests/Methods/Slot/test_SlotMFlat2_meth.py: This is great that you have included a test for your code! Can you put your test within a function or a pytest class (by taking inspiration from the other test)? Otherwise when we load and gather all the test, yours will be fully executed (which can block the loading process in case of error).

Best regards,
Pierre

**Comment by BonneelP** [comment]
Hello, 

I have updated the test and merged your PR. Thank you again for your contribution :)

Best regards,
Pierre

**Pull request merged**
