### PR TITLE
[CC] lambda function strings

### PR DESCRIPTION
**Pull request by SebGue**
This PR updates some lambda functions to lambda function strings (according to #172).
It also add the possibility to use np and random in the function string, e.g. `func_str = "lambda x, np=np: np.abs(x)"`
(This seems a little odd, but will work for now. Maybe someone has a better solution.)

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello,

I run some check on my side, as long as the package is imported there is no need to provide it as argument of the lambda.
I will update the class generator to always import numpy as np and random when a function is provided. A test including np. will be added in test_post_var_simu

Thank you for this contribution :)
Best regards,
Pierre

**Comment by SebGue** [comment]
That's really strange. I get the 'random' of 'np' not definded error???

**Comment by BonneelP** [comment]
Strange indeed :/ I noticed that some of your lambda already didn't have np. as argument. Maybe it is linked to some lambda ? Normally eval create the lambda in the context of the class file which have the corresponding package so we shouldn't have to provide np as argument. I just pushed the corresponding modification, I will run all the tests to make sure.

**Comment by SebGue** [comment]
I have double checked. I also thought it should be sufficient to have np/random imported at lambda definition, but it was not.
I set a breakpoint in at lambda definiton in 'def _set_get_value' of OptiDesignVar to check the import, i.e. `dir()` showed that random was imported. Nevertheless exactly this design var resulted in the mentioned error.
BTW: With your latest commit, do you import random and np at every class?

**Comment by BonneelP** [comment]
On my side all the tests are Ok. Which version of python are you using ? I'm on 3.8.6
In the latest commit I import random and np for all the class that have at least one property of type "func"

**Comment by SebGue** [comment]
Oh... I haven't seen the 'if func' :-)
I am on 3.8.3
Maybe it will work with the 'global' class import. I will try.
Have you checked the 'if 'np.' in value' import as well?

**Comment by BonneelP** [comment]
We I first tested it before my commit, I was already using "global" class import so that can be the explanation for the difference :)

**Comment by SebGue** [comment]
That's it. With global class import the error is fixed. 
So I quiet have to learn a lot regarding python :-)

**Comment by BonneelP** [comment]
Great :) I think that luck help me a bit on this one ;)
I have push an improvement for #183 as well. I'm running all the tests one last time if it is Ok I will merge #170, then update the tutorials and create the release 1.0.1 for the webinar.

**Pull request merged**
