### PR TITLE
[BC] ClassGen, copy method

### PR DESCRIPTION
**Pull request by SebGue**
Had some strange optimization results ... took me hours to find the bug :-(
I thought `type(obj)(init_dict=obj.as_dict())` would deep copy a pyleecan object (e.g. used in copy method), but it doesn't.
At least if the object contains a dict.
This PR fixes this behavior as long as the dict has only mutable types in it. So it should only be a temporary workaround.
I think we should further investigate this issue also for lists. A possible solution could be a function that walk though all list/dict elements and serialize them as well.
Maybe we could also have a TestClass, i.e. a class specifically for unit testing only, that has all possible combinations of property types in it, to avoid such issues in future.

Best regrads, Sebastian

BTW: This PR has #182 in it. I hope this is not a problem.

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello,

Thank you for noticing. I discussed about it with Cedric and he propose that we use [copy.deepcopy](https://docs.python.org/fr/3/library/copy.html) for dictionary and list. 
Indeed we can add a "_AllGenPossiblePropTest" class and it should be tested alongside all the others. 
Should we merge this PR and open an issue to remind us about the other necessary modifications ? Is there a way so that we can contribute to your PR (other than modifying the code from Github) ? 

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

you can merge this PR. 
Is copy.deepcopy able to copy pyleecan objects as well?

> Is there a way so that we can contribute to your PR (other than modifying the code from Github) ?

I don't know exactly what you mean or what you want to do. If you want to modify my PR before merge, you could pull my ClassGen branch into a new branch on your repo and I close this PR. But I guess you already know.

Best regards, Sebastian

**Comment by SebGue** [comment]
... or do you think of something like that: [Invite Collaborators](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository)

**Comment by BonneelP** [comment]
Hello,

Yes I was looking for a solution like "invite collaborators" but without the invitation ^^' Anyway, I will merge this PR and do the suggested modifications on PR FEMM (it is fully validated now and will be merged soon. It will be the ref for release 1.0.1)

Thank you again for this contribution :)
Best regards,
Pierre

**Comment by SebGue** [comment]
I send you  an invitation though. Just to test this feature. I will also add an issue where I will collect some thoughts uptill tomorrow.
Should I also invite someone else?

**Comment by BonneelP** [comment]
Thank you for the invitation :) We can talk about other invitation tomorrow.
The commit above introduces the use of copy for list as well. In as_dict for list and dict of both ndarray and pyleecan object we already create a new dict and list and call as_dict or tolist (return a copy of the array) for each element. So as long as the dict and list don't contain object it should be Ok (and in that case we should use [obj] for instance and we should be able to detect it).

**Pull request merged**
