### PR TITLE
[CO] Merging SlotMag and SlotWind

### PR DESCRIPTION
**Pull request by BonneelP**
Hello all, 

I have finished my work on the SlotMerge branch :) As a reminder the point was to merge SlotMag and SlotWind into Slot to answer #169. 
All the magnets have been converted to SlotMX classes. We managed to create a SlotUD2 class that directly take the active surface as a property and produce the following FEMM simulation: 
image
The GUI and the Tests also have been updated. Now the GUI Magnet step is mostly the same thing as the usual slot one (except for magnet material and magnetization).
LamSlotMag have been reorganized to have only one magnet instead of a list of magnet but one can easily create a LamSlotMagMulti class to get the previous behaviour. To go further one can also investigate splitting magnets the same way we do for winding. 
This PR also solve the import of some dxf Arc and introduce a new "BoreUD" class (that one day will go along a dedicated dxf import widget).

The schematics in the GUI have not been updated (W0 is missing on all SlotMX) but we plan to work "automatized" schematics in a near future. Finally there is still some docstrings and comments that need to be updated to rename "winding" into "active"

I won't merge this PR before a while to let everyone inspect/improve it. Note that it break retro-compatibility: all machine using LamSlotMag object need to be updated (Hmag and Wmag from magnet to slot, update slot type, update magnet type, remove W3 from slot, move magnet from slot to lamination). All existing validation machine have been updated. Once this PR merged, we plan to do a new release so that the new standards are used as soon as possible. This release will be 1.1.0 and the roadmap will be updated afterwards. 

Best regards and merry christmas,
Pierre

### CODE REVIEW

**Comment by SebGue** [comment]
Hello Pierre, 
thank you for that PR. I guess this was a lot of work. I hope I can finally have a look at it the next days. :-)
Is there some tutorial on how to split windings? I think I missed that.
BR and Merry Christmas, Sebastian

**Comment by BonneelP** [comment]
Hello Sebastian,

The "active surface" is automatically split in the file pyleecan/Methods/Slot/Slot/build_geometry_active.py and some improved versions can also be available in the SlotWX classes (for instance pyleecan/Methods/Slot/SlotW10/build_geometry_active.py).
As a side note: the method to split can be improved by changing the return of the split_line method to always return both top and bottom part (to avoid calling twice the method). I will open an issue or work on that once I'm back from holidays.

Best regards,
Pierre

**Comment by BonneelP** [comment]
Hello all,

I have added a new experimentation in this PR. The "SlotW10.plot_schematics" method to plot the schematics either on default or current slot. Can someone check if the general file organization is Ok or if there is any other feature or variable to add ? If this template is Ok I will start to add this method for all the other slots (which can take a while). Here is how it looks like with default slot and a save_path:
test

Best regards,
Pierre

**Comment by BonneelP** [comment]
Hello, 
As requested, I have added a function to convert the init_dict when loading an old version of a SIPMSM machine. This function (and the corresponding test) will be extended after each new reorganization. 

Best regards,
Pierre

**Pull request merged**
