### PR TITLE
MagnetType15 - polar bottom, curved top, parallel sides

### PR DESCRIPTION
**Pull request by SebGue**
Hello Pierre,

although you are preparing the unified slots, I would like to add an other magnet type.
The implementation is not perfect, because the actual slot is not parallel. Nevertheless it may be useful to some.

BR, Sebastian

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello Sebastian,

No problem for that, in fact that way we can challenge the organization to make sure that this magnet can also be defined (which should be the case). Can you add some test so I can be sure that the new organization won't break your magnet ? 

Best regards,
Pierre

**Comment by BonneelP** [comment]
Hello Sebastian,

I see that there is a commit "MagnetType15 top curve bug fixed", should I merge this PR now ?

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

no these are other CC I added meanwhile. I still work on the unit tests. But with my next commit you can merge the PR.

BR S

**Comment by BonneelP** [comment]
Thank you for your contribution :)

**Pull request merged**
