### PR TITLE
[CO] Label reorganization

### PR DESCRIPTION
**Pull request by BonneelP**
Hello all,

Here it finally is: the PR related to issue #344 that reorganize all the labels and improve the structure of the coupling with FEMM (which will enable to simulate more complex machines). This PR is also linked to the PR 5 of the pyleecan-doc repository (to add a page on label convention and another one on hole conventions).

The main modification are the following:
- Functions/labels now gather all the labels and related functions
- FEMM functions reorganization to use new label and function (in particular get_obj_from_label)
- Line.label is now Line.prop_dict to set several property on a line for different coupling
- Lamination.get_label 
- New schematics for the related new documentation pages

This PR is not fully finalized, I still need to update the GMSH/Elmer related tests (all other tests are working). I'm not familiar with these part of the code so I will do my best to maintain the current behaviour with the new labels. We may also take the opportunity to improve the mesh definition in FEMM. 

@SebGue when you will be back from your holiday, I would be glad if you can check if these modifications are Ok for you or if we can go one step further. Meanwhile we will work on a branch based on this PR so no rush ;)

Best regards,
Pierre

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello all, 

I took the time to update the coupling with GMSH:
- The sliding band labels are been renamed to be consistent between FEMM and GMSH. One day we should be able to add a Machine method get_sliding_band that can be use by several coupling. In particular "line_1" and "line_2" are now renamed "Right", "Left" and "Radius" for a better understanding (even in FEMM where it doesn't matter)
- A new function "draw_surf_line" to draw the lines of a surface has been introduced to remove some repetitive code lines and to split the draw_GMSH file into two files. 
- A new function "short_label" is now available in Functions.labels to return a Elmer compatible version of the new labels (that are already shorter than before)
- To go further the machine generation is split in 4 steps (Rotor, Stator, Sliding Band and Airbox) that may be gathered in a single function to remove some duplicated code. Which could be the opportunity to prepare an extension for more complex machines (more than two lamination, external rotor, no shaft...)
- As the lines don't have label any more, the mesh_dict was reorganized as key: surface label, value: dictionary with line index = number of element. The issue is that it is not really convenient to count the line to know where to set the mesh. I may investigate a better system latter on that could either select a line according to its index or a property (a line with a property dict is by definition an interesting line to interact with). test_gmsh2 is working but the mesh_dict was not updated.

The coupling with GMSH works, now the final step is to make sure that MagElmer and StructElmer are not broken (which, as I'm not really familiar with this part of the code, is totally possible). 

Best regards,
Pierre

**Comment by BonneelP** [comment]
Hello all, 

I'm done with this PR now. All the tests (including Elmer related ones) are passing. 

The MagElmer and StructElmer coupling were updated to use the new labels (as for FEMM coupling it will enable to go further with both of these couplings). Although the tests are passing, it seems that there are still some issues with StructElmer but the issues were there before the work on the labels. The new label convention should ease the correction/improvement of StructElmer but I think that it can be done in another PR. 

We recently realized that although the Ventilations classes were daughters of Hole, their behaviour were not consistent. In particular VentialtionX.build_geometry returned Zh surface instead of one. It was corrected in 7dcb3c361866e6987584822b7433a0a2782b6e1f

I will let this PR open to review for few days before merging. Once merged I plan to release pyleecan 1.4.0, update the website and share the first executable with the scripts from #416. Hopefully on next Friday.

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

you asked me to have a look at this PR, but I had no time to really get into it. So sorry not reviewing.

BR S

**Comment by BonneelP** [comment]
Hello Sebastian, 

Don't worry that's normal. This PR was quite long to review so we did the review internally. The changes were more and more required for other work and it could have created unnecessary conflict. As all the tests were fine/updated I took the initiative to merge it, I hope you don't mind.

Any way, we are still open for any feedback, in particular the PR regarding the documentation is still open on the dedicated repository (hopefully I will come back to it this week to rewrite the installation page). Then if any further work/refactoring is required we can open a new dedicated issue (maybe the prop_dict for line can be improved). 

Best regards,
Pierre

**Pull request merged**
