### PR TITLE
Frame gap

### PR DESCRIPTION
**Pull request by ecs-kev**

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello, 

Thank you for your contribution :) As a follow up to issue #407 here are some hints/remarks on the next steps for your PR:
- build_geometry, for further work, in some FEA software we may also need to return the air surfaces (in particular FEMM will need it).
- build_geometry_bar & comp_surface_bar, I don't know if it was intended but the bar looks polar instead of rectangular. Can you update the csv definition to specify if the bars are polar or rectangular ?
- build_geoemtry_bar, for now there is no symmetry in this function (but it can be tricky if the cutting line is on a bar). So we can leave it and wait for issue #24 
- comp_surface: to be consistent with the other method, can you update it to return the full surface (frame + bar) ? Then no more need for the comp_volume method.

Regarding the tests:
- For each method to test you need to define a function like in Tests/Methods/Machine/test_desc_dict.py. Pytest will understand that each function is a different test and if one fails it will run the others. To test your code, you can then add a "if __name__ == "__main__" and call directly the functions.
- The test for the three methods looks fine (for simple function a single call can be enough if there is no particular case). Can you add a test on comp_surface which is the generic methods that is used to compute the mass of the frame ? 
- To test the build_geometry functions, you can create a machine plot test like Tests/Plot/test_LSPM.py

Hope these few hints will help, feel free to ask otherwise :)
Best regards,
Pierre

**Comment by ecs-kev** [comment]
Hey,

Thanks for your comments. I implemented them and will update the PR shortly.

Regarding the questions/comments:
1) I left this for now, but it should be straight forward to implement if required.
2) Yes, they are intended to be polar. I updated the csv defintion. In reality, they are generally rectangular and fit into a slot in the frame and stator, but I decided against implementing this for simplicity (and because the impact on modelling results will be negligible). 
3) I wasn't sure how to implement the symmetry, so I left it out. Will revisit it when #24 is completed.
4/5/6) Implemented all of these changes.

Kind regards
Kevin

**Comment by BonneelP** [comment]
Hello, 

Sorry I just realized that this PR is still open. With all the modifications from your latest commit for me it is ready to merge. Is there anything else you wanted to add ? (For the model related method, we can use another PR)

Best regards,
Pierre

**Comment by ecs-kev** [comment]
Hi Pierre,
No it's ready to go from my point of view. If you're happy to merge it as it is, please go ahead.
Regarding the model related method: Are you referring to the comp_height_gap_frame() method?
Kind regards
Kevin

**Comment by BonneelP** [comment]
Hello,

By model related method I was referring to what you mentioned in the issue (CAD coupling and thermal computation). Basically, if we consider that this Pull Request "only" adds the geometry methods for the frame then we can consider it "merge-able". But indeed we can't do much with it for now so we can wait to have a proper application before merging it. 

I was just worried that you were waiting for the PR to be merged. If you prefer to wait, that's good for me, I will wait your next commits and green light to review/merge ;)

Best regards,
Pierre

**Comment by ecs-kev** [comment]
Hi,
Would be nice to get it included as it is now, as I won't be able to get any further work done on this for the next few weeks as I'll be on holiday.
Cheers
Kevin

**Comment by BonneelP** [comment]
Thank you for your contribution :)

**Pull request merged**
