### PR TITLE
[CO] Reorganize Magnetics and MagFEMM input and outputs

### PR DESCRIPTION
**Pull request by EmileDvs**
This PR aims at solving issue https://github.com/Eomys/pyleecan/issues/200

The PR is work in progress, I'll update it as things progress.

### CODE REVIEW

**Comment by EmileDvs** [comment]
The Magnetics and MagFEMM objects are now updated with the changes detailed in https://github.com/Eomys/pyleecan/issues/200

The standards outputs of any Magnetics models are stored in the end of Magnetics.run(), e.g. B, Tem, Phi_wind_stator data objects.

Outputs that are only related to MagFEMM are stored in the end of MagFEMM.comp_airgap_flux(), e.g. the MeshSolution containing mesh information and magnetic quantities per elements. To do so I had to improve the FEMM parallelization, in particular reuse solve_FEMM in solve_FEMM_single function of solve_FEMM_parallel. FEMM parallelization can be further improved following new issue https://github.com/Eomys/pyleecan/issues/208.

Sebastian, Alejandro, I think we should update the MagElmer architecture as well, in particular removing the part that store standards outputs because it will be done in Magnetics.run(). Please let me know if you need any help on this!

**Comment by SebGue** [comment]
Hello Emile, is this PR ready to merge or is it still wip?

**Comment by SebGue** [comment]
Hello @EmileDvs, hello @BonneelP ,

since you are working on solve_FEMM, I ask my question here.
Could there be class specific code in solve_FEMM, e.g. `if isinstance(winding, WindingSC)`? I tend to say no. But maybe you got other opinion.
Background is, that actually periodicity (a) with induction machines doesn't work, i.e. periodicity is calculated and set correct for the model but the expected number of phases (by solve_FEMM to get the circuit props) doesn't match. So there is an error.

BR, Sebastian

**Comment by EmileDvs** [comment]
Hello @SebGue,

I agree with you, what I did is not clean at all. As you pointed out, the space periodicity do not apply on rotor phases of SCIM. What we want is to specify to comp_I_mag only the rotor phases (i.e. the rotor bars ID) that will be drawn in the model and for which currents must be calculated. In conclusion, this is all about taking into account periodicities at the beginning of each model, and we can do as we did for time and angle. My new proposition is to store the phase axes (both stator and rotor) in the axes_dict that we pass to comp_flux_airgap.

Still, in comp_time_angle we still have to check whether spatial periodicity contained in Angle axis apply to stator/rotor phase axes, i.e. to check in the winding is a "WindingSC". Because we don't want to apply it the other windings types.

While you may come up with a better proposition than mine, I am modifying the pull request to implement the phase axis in comp_time_angle (that we should probably rename comp_axes, as it is already the case in gen_input).

Best regards,
Emile

**Comment by SebGue** [comment]
Hello @EmileDvs ,

that's fine to me. Just to conclude: You will do the 'general' reorganization and I will add the special case.
My idea is to use the Laminations comp_per. method to calculate the models qs (number of phases) and reconstruct the other phases props. afterwards (utilizing 'wind_mat').
BR, Sebastian

**Comment by EmileDvs** [comment]
Hello @SebGue,

Ok then the most simple is not to implement periodicity on phase on the present pull request. We can open an issue later to solve this problem for Squirrel Cage Induction Machines specifically.

Best regards,
Emile

**Comment by EmileDvs** [comment]
After discussion with @BonneelP  and @helene-t, I have created the issue related to the phase axes in https://github.com/Eomys/pyleecan/issues/211. 

We also decided not to merge this PR before the next webinar in order to improve a bit further the way magnetics data coming from MagFEMM.comp_flux_airgap() are saved in the Magnetics.run(). 

The idea is to return all the outputs as dict (out_dict), for example out_dict["Br"] contains Br.

Then we implement a Magnetics.store_output(out_dict) method that will store all standard outputs in OutMag if they are in the dict.

Finally, MagFEMM and MagElmer will have their own store_output() method, which will first call Magnetics.store_output(out_dict) and then store the additional data. 

That way it becomes obvious where output storage should be implemented, and there is no problem in the future to add other outputs to the MagFEMM/MagElmer model.

**Comment by BonneelP** [comment]
out_dict contains the matrices (with proper periodicity), store_out creates the corresponding Data objects and set them in the Output object.

**Comment by SebGue** [comment]
Hello @EmileDvs , hello @BonneelP ,

I have nearly finished the a first working version of EEC_SCIM and would like to already include this PR. So could you tell me if there are still fundamental changes to come? Further I will introduce mag.Phi_wind_list corresponding to get_lam_list to store the fluxlinkage of multiple Lamination (2 for now) if you don't mind.

BR, Sebastian

**Comment by EmileDvs** [comment]
Hello @SebGue,

It should be done anytime soon, we are currently running the tests. 

Concerning the idea of having a list of Phi_wind, currents, voltage per lamination I think it is something @BonneelP has been willing to do for a long time. Maybe we should open an issue on this, which can be dealt in the same PR than the other issue (https://github.com/Eomys/pyleecan/issues/211) related to modifications on lamination currents.

Best regards,
Emile

**Comment by BonneelP** [comment]
Thank you for your contribution :)

**Pull request merged**
