### PR TITLE
[NF] Multisimulation on Multisimulation

### PR DESCRIPTION
**Pull request by SebGue**
This is a proposal of an implementation to do multisimulations on multisimulations that is not finished yet.
I will open an issue to discuss the details as soon as possible.

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello all,

I have added the latest modifications and corrected the "not long" test so I think that this time I'm really done with this PR :) Sebastian, can you run/correct the long ones (I won't have the time to do it) ? If there is no major modifications, you can merge it.  Otherwise I should take some time to come back to this PR during my holidays. Thanks again for your work on this PR. 
Once I will be back from Holiday I plan to release a new version of pyleecan (1.2.0).

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

I can do that but I don't know if it will be this week. Do you have some official representative for your holiday?

Best regards, Sebastian

**Comment by SebGue** [comment]
Hello Pierre,

I fixed the 'test_FEMM_loss'. In short, there seems to be some issue with the old MagM12 definition that caused this error.
I haven't merged yet, since I still get some more ('not long') errors, that should be fixed first.
BR S

**Comment by BonneelP** [comment]
Hello all,

I have corrected some "long" tests and everything is fine on my side :) Should we merge this PR ?

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

I get a lot of annotate errors, e.g.

`FAILED Tests/Plot/Schematics/test_plot_schematics.py::Test_plot_schematics::test_hole_no_mag[test_dict0] - TypeError: annotate() missing 1 required positional argument: 's'`

So I would like to check that. Maybe I'm just out of date with my requirements.

Best regards, Sebastian

**Comment by SebGue** [comment]
... what's your matplotlib version? I was at 3.2.2 and now updated to 3.3.4, which solved the issues. So we maybe have to update the requirements that tells 3.2.1 
On the 'not long' tests, there is only an save_emit error left. Does this test work on your side?

```
================================================================ ERRORS =================================================================
_____________________________________________ ERROR at setup of TestSaveEmit.test_save_emit _____________________________________________
file D:\GitHub\PyleecanLokal\master\pyleecan\Tests\GUI\DMachineSetup\test_SaveEmit.py, line 39
      def test_save_emit(self, setup_method):
file D:\GitHub\PyleecanLokal\master\pyleecan\Tests\GUI\DMachineSetup\test_SaveEmit.py, line 25
      @pytest.fixture
      def setup_method(self, qtbot):
E       fixture 'qtbot' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, setup_method, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

D:\GitHub\PyleecanLokal\master\pyleecan\Tests\GUI\DMachineSetup\test_SaveEmit.py:25
```

**Comment by BonneelP** [comment]
Hello,

Regarding matplotlib, I'm using 3.3.2 and it work on my side. So Ok to change the version to 3.3.2 in the requirements. 
Regarding the second error it may be a hidden requirements. pytest-qt maybe ?

Yes I think that this implementation enables to parallelize each run of a var simu (except the reference one). But it is something that we can discuss in another issue after this PR ;)

Best regards,
Pierre

**Comment by BonneelP** [comment]
Great. Thank you for your help :)

**Pull request merged**
