### PR TITLE
[NF] New Slot schematics and GUI improvements

### PR DESCRIPTION
**Pull request by BonneelP**
Hello all, 

This PR introduces the method "plot_schematics" for all the Slots and Holes from the GUI (except for SlotW60 and SlotW61). There is a new folder Tests/Plot/Schematics to gather all the tests that enables to create schematics and other figures. All the new schematics have been added in the GUI (SMachineDimension, SMSlot, SWSlot, SMHoleMag with and without magnet) and some modifications were done to improve the resize behaviour of the corresponding widgets. Now all slot and holes have a "_comp_point_coordinate" method that returns a dictionary which is easier to handle than the previous list. 

plot_schematics have a "is_default" parameter that would enable to plot the schematics on any slot which would enable to create dynamic schematics for the corresponding widgets. But it would require further improvement for all the schematics in particular to handle cases like H1=0 and to have a proper placement for the labels. 

@SebGue I took the time to reorganize a bit the build_geometry of HoleM50, I hope it will help you. I guess this image will:
HoleM50_point
(From Tests/Result/Plot/Schematics, available for all slot/holes, you can create a zoom out version as well)

The build_geometry_active of some slot was also corrected and a new generic test can check that the proper surfaces are generated with the proper label. The tests for the schematics of all slots were improved (and SlotW24 was corrected after that). It won't harm to use the same principal for all holes in particular HoleM58 looks wrong. 

Finally to normalize some import, Exception definition were moved from methods files to __init__ files.

Best regards,
Pierre

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello all, 

I have merge all the latest pull request into master and then into this PR. Then I run all the Tests and here is the results:
- Tests/Methods/Mesh/test_get_solutions
image
image

- Tests/Validation/Simulation/test_EM_SPMSM_FL_002
image
image

- Tests\Validation\Simulation\test_FEMM_Loss
image
- Tests\Validation\Simulation\test_FEMM_parallelization
image
image

- Tests\Validation\Simulation\test_FEMM_periodicity
image

I guess most of these errors are from the master. I will investigate them to be able to create the next release, all help is welcomed :)
Best regards,
Pierre

**Comment by SebGue** [comment]
+ there seems to be an issue with SWindPat line 290: self.obj.plot_activeing() ->AttributeError: 'LamSlotWind' object has no attribute 'plot_activeing'

**Comment by BonneelP** [comment]
Thank you for noticing, I fixed it :)

**Comment by Superomeg4** [comment]
The bug from Tests/Methods/Mesh/test_get_solutions occurs with the last modifications from SciDataTool.

**Comment by BonneelP** [comment]
Thank you for the correction :)
It seems that the latest modifications is SciDataTool + Raphael PR #310 have solved the issues in the master.
I plan to carry on the work on the GUI to improve few other pages (plot_schematics for winding conductors for instance) and I should merge this PR and do the release on Friday (if it's Ok for you).

Best regards,
Pierre

**Comment by SebGue** [comment]
It is okay for me.
I also got some branches to merge, so I hurry up :-)

**Comment by SebGue** [comment]
... I added Mag15 to gui so you dont have to.

**Comment by SebGue** [comment]
Found some other issue with the 'parent of list element' commit, if element is None. I will fix this.

**Comment by BonneelP** [comment]
Hello all,

I pushed the last commit for this PR. Everything looks right so far, I plan to do some further check this afternoon and merge + release at the end of the day.

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

this really looks good. 
One thing I recognized is, that the rotor plot of IPMSM doesn't show off. Maybe you could have a look.

Best, Sebastian

**Comment by BonneelP** [comment]
Hello Sebastian,
Thank you for noticing, it was linked to a test that need to be updated (I think that the clicked signal already returns a boolean).
I just saw that you made your other PR on our other repository, I will review them

Best regards,
Pierre

**Pull request merged**
