### PR TITLE
Implementing curve fitting to compute loss coefficients.

### PR DESCRIPTION
**Pull request by astonysheen**
This PR enables the loss models to compute their loss coefficients by curve fitting, using the loss data stored in the magnetic materials.
This Pr is to be merged after Elec_Loss (already done)

### CODE REVIEW

**Comment by BonneelP** [comment]
It is maybe some bugs on master. In particular I guess the last 2 ones are related to plot_multi

**Comment by SebGue** [comment]
The elmer (struct) tests are my long term tasks so you may ignore them for now.

**Comment by astonysheen** [comment]
I ran the tests after merging the master in the branch : 
`====================================================================== short test summary info ======================================================================= 
FAILED Tests/Classes/test_classes.py::test_class_methods[class_dict112] - ImportError: Can't use OptiBayesAlgSmoot method solve: No module named 'smoot'
FAILED Tests/Classes/test_classes.py::test_class_methods[class_dict165] - ImportError: Can't use MagElmer method comp_flux_airgap: No module named 'gmsh'
FAILED Tests/Classes/test_classes.py::test_class_methods[class_dict178] - ImportError: Can't use StructElmer method gen_mesh: No module named 'gmsh'
FAILED Tests/Functions/test_gmsh.py::test_slot_10 - TypeError: ImportError() takes at most 2 keyword arguments (5 given)
FAILED Tests/Functions/test_gmsh2.py::test_gmsh_ipm - TypeError: ImportError() takes at most 2 keyword arguments (9 given)
FAILED Tests/Functions/test_gmsh2.py::test_gmsh_spm - TypeError: ImportError() takes at most 2 keyword arguments (9 given)
FAILED Tests/Functions/test_gmsh2.py::test_gmsh_benchmark - TypeError: ImportError() takes at most 2 keyword arguments (9 given)
FAILED Tests/Methods/Mesh/test_plot_contour.py::test_plot_contour_1group - ValueError: Number of scalars (3) must match either the number of points (0) or the numbe...FAILED Tests/Methods/Mesh/test_plot_contour.py::test_plot_contour_2group - ValueError: Number of scalars (6) must match either the number of points (0) or the numbe...FAILED Tests/Methods/Mesh/test_plot_mesh.py::test_plot_mesh - ValueError: Empty meshes cannot be plotted. Input mesh has zero points.
FAILED Tests/Methods/Simulation/test_magelmer.py::test_ipm_Elmer - ImportError: Can't use MagElmer method comp_flux_airgap: No module named 'gmsh'
FAILED Tests/Methods/Simulation/test_magelmer.py::test_spm_Elmer - ImportError: Can't use MagElmer method comp_flux_airgap: No module named 'gmsh'
FAILED Tests/Plot/test_ICEM_2020.py::test_gmsh_mesh_dict - ImportError: Fail to import gen_3D_mesh (gmsh package missing)
FAILED Tests/Simulation/test_StructElmer.py::Test_StructElmer::test_StructElmer_HoleM50 - ImportError: Can't use StructElmer method gen_mesh: No module named 'gmsh'   
FAILED Tests/Simulation/test_StructElmer.py::Test_StructElmer::test_StructElmer_HoleM50_no_magnets - ImportError: Can't use StructElmer method gen_mesh: No module n...FAILED Tests/Simulation/test_StructElmer.py::Test_StructElmer::test_StructElmer_disk - ImportError: Can't use StructElmer method gen_mesh: No module named 'gmsh'      
FAILED Tests/Validation/Optimization/test_Binh_and_Korn_Bayes.py::test_Binh_and_Korn - ImportError: Can't use OptiBayesAlgSmoot method solve: No module named 'smoot'  
FAILED Tests/Validation/Optimization/test_zdt3_Bayes.py::test_zdt3_Bayes - ImportError: Can't use OptiBayesAlgSmoot method solve: No module named 'smoot'
=============================================== 18 failed, 5149 passed, 27 skipped, 50 warnings in 2907.21s (0:48:27) ================================================ `
Most of the failed tests are due to gmsh, elmer or smoot that I do not use. 
However, I do not know why the tests related to mesh fail.

**Comment by BonneelP** [comment]
All tests are Ok, thank you for your contribution :)

**Pull request merged**
