### PR TITLE
 GUI LamHole mag_mat select for every magnet

### PR DESCRIPTION
**Pull request by SebGue**
Added w_mat_select widgets to select the magnet material of every magnet of a LamHole lamination.
Also 'blacked' the GUI files which is maybe not necessary.

### CODE REVIEW

**Comment by SebGue** [comment]
Hello Pierre,
I think, I'm finished here for now. 
Best regrads, Sebastian

**Comment by BonneelP** [comment]
Thank you for your contribution ! 
I didn't merge it before because of the conflict. Thank you for your last commit !

**Comment by BonneelP** [comment]
As a further evolution, what about having the material setup directly in the "PHoldM5X" widgets ? When combining several kind of holes or several layers of the same hole we may want to define different materials. Do you think that we should investigate the possibility to set a magnet to "None" ?

**Comment by SebGue** [comment]
There are several things coming together here and I will try to address them but only in short:
Direct material setup would be good, since the material setup is already per hole. But that's not clear for the user at the moment.
Therefore a more "automated" GUI would be great IMO (cf #58 ).
I think we already disussed "None" magnets in the past, but I didn't checked yet. Nevertheless I like the idea.
I think hole magnets are a little inconsistent at the moment since they are no "real" magnets, i.e. they are no MagnetTypeXY and have different of methods (get_height_magnets vs. comp_height).
If I remember correctly multiple holes are not implemented till now. Only the first hole is regarded.

**Comment by SebGue** [comment]
One more thing: It would be good to have the possiblity to include a magnet gap to include manufacturing tolerances for instance. Maybe it is sufficent if the gap will be "virtual", i.e. by modifing the material parameters of the magnets.

**Comment by BonneelP** [comment]
To be more clear on the schematics we should add a label with the magnet number. 

I just realized that everything is called "slot" on the widget related to "holes", should we rename it ?

If a magnet of a HoleM5X is set to None, the build_geometry will remove the corresponding surface which is quite interesting.

Indeed for now all magnets are rectangular and defined by the hole itself. Maybe for later development we can say that the hole define the area dedicated to drawing the magnet and the Magnet object would change how it is defined.

It is already possible to define several holes with the GUI with the button "add new slot". That's why having the material setup in SMHoleMag is tricky if there are several kind of holes with a different number of magnets.

**Pull request merged**
