### PR TITLE
[NF] Struct elmer

### PR DESCRIPTION
**Pull request by SebGue**
Although there is still some work to do on structural simulation with Elmer, I will PR this now.
So everyone can utilize and contribute to the convenience class 'Elmer' that is thought to do all the IO between pyleecan and Elmer.
Regarding the structural simulation, it is only centrifugal force calculation with pure lamination or HoleM50 with magnets for now.
For getting started, there are some tests.

For the complete details on this new feature, I will put them in #231 as soon as I got some more time.

BR Sebastian

### CODE REVIEW

**Comment by ajpina** [comment]
Great @SebGue,
What type of contact conditions do you use between magnets and laminations? Is there any kind of frictional coefficient involved?
Best,
Alejandro

**Comment by SebGue** [comment]
Hi @ajpina , just in short. The normal displacement between the contacts is periodic, while the tangential displacement is independent. This should simulate a sliding contact, so no friction or glue is regarded. 
The detailed why's and how's will follow in the respective issue the next days.
BR Sebastian

**Comment by BonneelP** [comment]
Thank you for your contribution :)

**Comment by carbon-drive** [comment]
Hi,
I think this is a great feature. Is there anywhere a tutorial on how to use this feature? 

I would love to start from it and add a carbon-fiber sleeve to the structural model and study its effects on the deformations. Also I would like to add a temperature loadcase to the Elmer-Model as this greatly effects the pretension of the sleeve.

Am I correct here or should I post this question somewhere else?

**Comment by SebGue** [comment]
Hello Martin,

thanks for you interest in this feature. Unfortunatly I still didn't have the time to add a tutorial. But if you may have downloaded this PR already, you can have a look at the test. I.e. in 'Tests/Simulation/test_StructElmer.py' you will find how to use the feature.
Further after running the test (or some adapted skript) the Elmer Case is generated in the respective result folder. So you can study the Elmer sif file.
Still there are some short comings especially regarding contact definition. So if you are interested, I greatly appriciate a discussion about it (which indeed should be in an own issue). (BTW: I'm not a mechanical engineer, so...)

Regarding sleeve, what rotor geometries do you want to study? Further do you think it's essential to have FEA sleeve simulation over some analytical calculations?

OT: Do you manufacture carbon sleeves in your company?

Best regards, Sebastian

**Comment by carbon-drive** [comment]
Hello Sebastian,

thank you for your quick response! I actually have a mechanical engineering
background and my main experience with FEM is centered on Abaqus so I am
unfortunately very new to Elmer. Yes we are actually manufacturing some
carbon sleeves for electric motors. We have developed a technology to make
very thin and highly prestressed sleeves. So far all my designs are based
on analytical calculations, but recently I got more and more requests for
sleeves with integrated magnets similar to what you simulated. And in that
case I am always very conservative and calculate it as if the steel
laminations don't have any strength of their own but are only added mass.
Or in a little bit more realistic approach, that there is a thin steel
sleeve and the additional cfrp-sleeve. But that still neglects all the
bending and shear deformations that are happening and that is why I wanted
to simulate it.

I already had a look at the code that builds the Elmer model, but was a bit
at a loss. I have modelled similar cases with cyclic symmetry BCs and
rotational body force but in Abaqus this is defined quite differently. So I
have to familiarize myself with Elmer more.

I will keep you updated.

Best regards,
Martin


Am Do., 20. Okt. 2022 um 21:09 Uhr schrieb Sebastian Günther <
***@***.***>:

**Comment by carbon-drive** [comment]
Hello Sebastian,

sorry that I am posting this here. I should probably move this somewhere better, maybe you can help me with this.

I updated my fork on github, then cloned the fork to my local machine. And then I first ran the 
`python -m pytest ./Tests -m "not long_5s"`

which yielded 29 failed tests all related to the "collections" module:

`AttributeError: module 'collections' has no attribute 'Iterable'` 

This must be related to my python version, but I ignored it for now and tried to run only the StructElmer test, which yielded the following:

```
PS C:\Users\Km\Documents\Salome\pyleecan> python -m pytest -m "StructElmer"
============================================================================================= test session starts =============================================================================================
platform win32 -- Python 3.10.5, pytest-7.1.3, pluggy-1.0.0
PySide2 5.15.2.1 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: C:\Users\Km\Documents\Salome\pyleecan, configfile: pytest.ini
plugins: anyio-3.6.1, hypothesis-6.56.3, qt-4.1.0
collected 5277 items / 5273 deselected / 4 selected

Tests\Methods\Simulation\test_ElmerResult_load_data.py .                                                                                                                                                 [ 25%] 
Tests\Simulation\test_StructElmer.py Windows fatal exception: code 0xc0000374

Current thread 0x00001158 (most recent call first):
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\gmsh-4.6.0-Windows64-sdk\lib\gmsh.py", line 1527 in refine
  File "C:\Users\Km\Documents\Salome\pyleecan\pyleecan\Methods\Simulation\StructElmer\process_mesh.py", line 335 in process_mesh
  File "C:\Users\Km\Documents\Salome\pyleecan\pyleecan\Methods\Simulation\StructElmer\gen_mesh.py", line 55 in gen_mesh
  File "C:\Users\Km\Documents\Salome\pyleecan\pyleecan\Methods\Simulation\StructElmer\run.py", line 22 in run
  File "C:\Users\Km\Documents\Salome\pyleecan\pyleecan\Methods\Simulation\Simu1\run_single.py", line 38 in run_single
  File "C:\Users\Km\Documents\Salome\pyleecan\pyleecan\Methods\Simulation\Simulation\run.py", line 52 in run
  File "C:\Users\Km\Documents\Salome\pyleecan\Tests\Simulation\test_StructElmer.py", line 75 in test_StructElmer_HoleM50
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\python.py", line 192 in pytest_pyfunc_call
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\python.py", line 1761 in runtest
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 166 in pytest_runtest_call
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 259 in <lambda>
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 338 in from_call
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 258 in call_runtest_hook
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 219 in call_and_report
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 130 in runtestprotocol
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 111 in pytest_runtest_protocol
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 347 in pytest_runtestloop
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 322 in _main
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 268 in wrap_session
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 315 in pytest_cmdline_main
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 164 in main
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 187 in console_main
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest\__main__.py", line 5 in <module>
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86 in _run_code
  File "C:\Users\Km\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196 in _run_module_as_main
```
Is it correct to run your test with pytest? I tried executing test_StructElmer.py by it own, but then it fails at the imports:
```
PS C:\Users\Km\Documents\Salome\pyleecan> python .\Tests\Simulation\test_StructElmer.py
Traceback (most recent call last):
  File "C:\Users\Km\Documents\Salome\pyleecan\Tests\Simulation\test_StructElmer.py", line 5, in <module>
    from Tests import save_validation_path as save_path, TEST_DATA_DIR
ModuleNotFoundError: No module named 'Tests'
PS C:\Users\Km\Documents\Salome\pyleecan>
```
Sorry if I am making some rookie mistakes. It is actually the first time I am trying to contribute to an open-source project.

**Comment by SebGue** [comment]
Hello Martin,

I think forking and cloning is one way to get the latest changes. Thats what I also do. Just make sure you include (i.e. pull) my "structElmer" branch since there are some essential fixes due to some changes in pyleecan. 

For running test_StructElmer.py you don't need to run pytest. You can run it on its own as you tried. Only you got to add pyleecan to the python module search path, i.e. 
```
import sys
sys.path.append('C:\\Users\\Km\\Documents\\Salome\\pyleecan')

```
You can add this to test_StructElmer.py. Or you move the test to the main pyleecan path so python can find the respective modules.

I started python when contributing to pyleecan the first time. Therefore I would still consider me a beginner. So don't worry :-)

For all the other points, I will come back later (this week).

Best regards, Sebastian

**Comment by SebGue** [comment]
... maybe you should also consider using some IDE, e.g. VS Code with Python plugin, to simplify your workflow.

**Pull request merged**
