### PR TITLE
[NF] Iron Losses

### PR DESCRIPTION
**Pull request by SebGue**
So finally, this is the first release of some classes to calculate the machine losses (especially the iron losses). 
I'm not quiet sure on how to organize the models and the calculated results. For now I decided to use a dict based structure.
There are 2 models for now, i.e. LossModelBertotti and LossModelWinding. More models to come in the near future, e.g. some general mech. loss models. There are as well some general changes, e.g. regarding the FEMM groups.

An example calculation can be found in 'Tests\Validation\Simulation\test_FEMM_Loss.py'.

Some feedback as well as validation cases are greatly appreciated.

EDIT: Unfortunatly I also pulled 'StructElmer' branch into this branch. Sorry for that. :-(

### CODE REVIEW

**Comment by Superomeg4** [comment]
Hi Sebastian ! 

I have reviewed your contribution. I was able to run it successfully on my computer. I think we can merge it for now as it is quite independant from the rest. 

Nevertheless, I would like to add in the documentation some references (for example an article which clearly explain the coefficients such as Bertotti or windings ...). Maybe we could find some results in such articles that we could try to reproduce with Pyleecan. 

Best regards,

Raphaël

**Comment by SebGue** [comment]
Hello Raphaël,

thank you for reviewing. Unfortunatly I recognized that the actual organization of the models and outputs is not serializable.
So I got to change that before. :-(

Open references for the iron losses could be the 'Vu Xuan Hung thesis' or the FEMM example from the test.
Do you think this is sufficient?

Best regards, 
Sebastian

**Comment by SebGue** [comment]
Hello @BonneelP 

could you have a look at my '[NF] allow None' commit. I think this could be useful sometimes.

Best regards, 
Sebastian

**Comment by SebGue** [comment]
I think I'm done for now with this PR. Tests (tested without GMSH and Force) seem okay. 
There are only some FEMM tests that 'lose focus' if I run all tests at once. If I run failed FEMM tests one by one they are okay as well.

**Comment by BonneelP** [comment]
Hello,

Thank you for this amazing work. This is a great step for pyleecan :)

Maybe one question: what is the purpose of pyleecan/load_dialog.py ? 

I'm Ok to merge it, then I plan to merge the PR #294 on log and update your code to use "Pyleecan.Loss" as a logger to match the new standard (in OutLoss and in Loss classes). Once merged, should I review/merge #287 and #291 (and in which order) ?


Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

I may added load_dialog.py by accident. So you can remove it. 
Yes you can review #287 and then #291.
For #291 there are also some additions at @ajpina PR. But I had no time to review. I also havent resolved Raphaëls comments there.

Best regards, Sebastian

**Comment by BonneelP** [comment]
Great I will have a look at #287 and I will wait a bit before merging #291
Thank you again :)

**Pull request merged**
