### PR TITLE
[NF] Generic Object Editor

### PR DESCRIPTION
**Pull request by SebGue**
This PR replaces the GUI's TreeView with a generic (pyleecan) object editor. The editor is related to #58 and mostly working.
Still there are some todos I got to implement, e.g. append/remove list or dict items, there is no link of the save state between both machine editors, ...

### CODE REVIEW

**Comment by BonneelP** [comment]
Hello Sebastian, 

Sadly I won't have the time today to review your PR. I'm planning to do it next week to include it in release 1.4.0 (As #428 and #419 may also need further modifications). Next there will be the exe generation and the website update.

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

don't worry, since there are still some open points to this PR (see TODO's above).
Nevertheless there is one thing you could think about. This new 'tool' is pulling some informations about the classes (inheritance, properties, prop. types, ...) from the classes dict (i.e. Class_Dict.json) to be able to set the correct prop. type. E.g. if one would like to replace a stator slot, the editor will give the option to set SlotW10, SlotW11, etc.
Now while SciDataTool (and Mosquito) are compatible, I haven't had a good idea how to pull the same information from these packages to include them in the editor the same way. Maybe there should also be a ClassesInfo class with these packages?
If you understand this 'issue' and have some idea, let me know.

Best regards, Sebastian

**Comment by BonneelP** [comment]
Hello Sebastian,

This PR is very interesting :) It will be really helpful to set the machine parameters that are not yet covered by the GUI. 
In particular, being able to interact with list/dict would enable to set the notches (on bore and yoke) which would be great ! What about having a line for each element of the list (hole then below hole[0], hole[1].... ?). Clicking on "hole" would enable to interact with the list length and then each line with the corresponding object.  

Regarding your issue with SDT / Mosqito, as we are going to add a GUI in SciDataTool it will more and more rely on the class generator. So in the near future we plan to extend it to add a "software" level to ease the generation process in all the packages (to remove progressively to links to pyleecan). We may even create a new separate repository for the class generator. With that in mind, we can assume that there will be a class_dict for each package which should be helpful ;)

Do you plan to continue the work on this PR or should we merge it and continue on another PR ?

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

you can merge this PR and I will increamentally implement the missing features.

The list/dict 'line per element' is already there. Only the add/remove is missing. 
I actually use this editor for all objects not only machines. You could 'hack' it and replace the object with maybe a XOutput object. But I'm not sure if you could do this after the GUI has started without crashing the app. So you may do this already at init.

A seperate generator sounds reasonable and the class_dict is really appriciated 👍 

BG S

**Comment by SebGue** [comment]
Done for now. With the recent commit, it is possible to load any object to the TreeEdit. The MeshSolution viewer is also included.

**Comment by BonneelP** [comment]
Thank very much for this contribution :)

**Pull request merged**
