### PR TITLE
[NF] GUI exe and installer

### PR DESCRIPTION
**Pull request by BonneelP**
Hello all, 

This PR introduces a new script to generate an executable to start the GUI and a dedicated installer. The idea is to add a new section on the website to upload an installer after each release. 

Best regards,
Pierre

### CODE REVIEW

**Comment by SebGue** [comment]
Hello @BonneelP ,

another question: Are there any (recent) plans to extend the GUI beyond machine editing? Or what's the reason for releasing the exec. generator at all?

Best regards, Sebastian

**Comment by BonneelP** [comment]
Hello Sebastian,

We are looking to ease the access to pyleecan. With the installer and the new button on the last step (cf #415) now pyleecan can be used as a mesh generator for electrical machine without having to install python or git. 

I take the opportunity to share our upcoming work on pyleecan:
- we are still working on the equivalent circuit for asynchronous machine (cf dedicated issues) that will reshape the Electrical module 
- we are planning to add the skew in MagFEMM and in the GUI
- we will add a GUI to SciDataTool (that will be available in pyleecan) to interact with the plot without knowing the syntax.

So no simulation GUI for now but if one day someone is interested to work of this topic, the executable will already be available.
Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

so there are some things coming together... :-)
I recently thought about releasing a generalized gui (also for simulations) due to the features of #420. (I have also added a simple MeshSolution viewer internally.)

> We will add a GUI to SciDataTool (that will be available in pyleecan) to interact with the plot without knowing the syntax.

That's great, so I don't have to care about this, since this would be some of my next things to do. One thing to discuss here may still be left, but I will open a new discussion right after this comment.

> We are still working on the equivalent circuit for asynchronous machine (cf dedicated issues) that will reshape the Electrical module.

I thought I already introduced some EEC for IM, but I forgot :-) Do you mean #379 or is there another issue?

Best regards, Sebastian

**Comment by SebGue** [comment]
... haven't tested yet, but is there also the ablility to export gmsh geo files, since meshes with general size assumptions may sometimes miss the intended purpose.

**Comment by BonneelP** [comment]
Hello,

Yes most of the pieces are slowly taking shape to provide one day a simulation GUI :) We can also extend #415 to parametrize the exports.

Yes the first EEC was a great help but we need to go further. In particular #372, #413, #418
We still have a lot to experiment so we haven't fully decided what the architecture should be. Other issues should follow.

Regarding gmsh geo, yes that would be interesting. We have added the gmsh buttons to introduce this feature to the users. We know that we can go much further but we lack contributors on the topic :/ 

Best regards,
Pierre

**Pull request merged**
