### PR TITLE
Skin effect

### PR DESCRIPTION
**Pull request by EmileDvs**
- Correct skin effect calculation resistance and inductance for all conductor types based on "Design of Rotating Electric Machines" book
- Add new conductor CondType13: rectangular conductor with round wires (strands)
- Add validation case for resistance, end-winding inductance and skin effect calculation

### CODE REVIEW

**Comment by EmileDvs** [comment]
To be merged after #510

**Comment by EmileDvs** [comment]
Ready to be merged after tests run and correction

**Comment by BonneelP** [comment]
(on computer without Elmer)
image

**Comment by EmileDvs** [comment]
> (on computer without Elmer) image

Thank you Pierre, I merged the master in the branch and corrected all the tests, now it should be ready for merge.

**Comment by BonneelP** [comment]
Thank you for your contribution :)

**Pull request merged**
